import logging
from src.models.contracts import UISchema

logger = logging.getLogger(__name__)


class HTMLGenerator:
    """
    Generates production-ready HTML pages from UI schema.
    Creates semantic HTML with proper structure and styling hooks.
    """

    @staticmethod
    def generate(ui_schema: UISchema) -> dict:
        """Generate HTML pages from UI schema"""
        pages = {}

        for page in ui_schema.pages:
            html = HTMLGenerator._generate_page(page)
            filename = f"{page.name.lower().replace(' ', '_')}.html"
            pages[filename] = html

        logger.info(f"[HTMLGen] Generated {len(pages)} HTML pages")
        return pages

    @staticmethod
    def _generate_page(page) -> str:
        """Generate a single HTML page with proper structure"""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page.name}</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <div class="container">
        <header class="page-header">
            <h1>{page.name}</h1>
            <p class="subtitle">{page.description or ""}</p>
        </header>

        <main class="page-content">
{HTMLGenerator._generate_components(page.components)}
        </main>

        <footer class="page-footer">
            <p>&copy; Generated by AI Application Compiler</p>
        </footer>
    </div>

    <script src="/static/js/app.js"></script>
</body>
</html>
"""

    @staticmethod
    def _generate_components(components) -> str:
        """Generate HTML for all components in a page"""
        html_parts = []

        for component in components:
            component_html = HTMLGenerator._generate_component(component)
            html_parts.append(component_html)

        return "\n".join(html_parts)

    @staticmethod
    def _generate_component(component) -> str:
        """Generate HTML for a single component"""
        name = component.name or "Component"
        component_type = component.type or "div"

        if component_type == "table":
            return HTMLGenerator._generate_table_component(component)
        elif component_type == "form":
            return HTMLGenerator._generate_form_component(component)
        elif component_type == "button":
            return HTMLGenerator._generate_button_component(component)
        elif component_type == "stat_cards":
            return HTMLGenerator._generate_stat_cards_component(component)
        elif component_type == "chart":
            return HTMLGenerator._generate_chart_component(component)
        elif component_type == "header":
            return HTMLGenerator._generate_header_component(component)
        elif component_type == "nav":
            return HTMLGenerator._generate_nav_component(component)
        else:
            return f'            <section class="component component-{component_type}">\n                <h2>{name}</h2>\n                <!-- Component content here -->\n            </section>'

    @staticmethod
    def _generate_table_component(component) -> str:
        """Generate table component HTML"""
        entity = component.entity_binding or "Items"
        columns = component.properties.get("columns", [])

        header_cells = "".join(
            f"<th>{col}</th>" for col in columns
        )

        return f"""            <section class="component component-table">
                <div class="table-header">
                    <h2>{entity} List</h2>
                    <button class="btn btn-primary">New {entity}</button>
                </div>
                <table class="data-table">
                    <thead>
                        <tr>
                            {header_cells}
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="{entity.lower()}-table-body">
                        <!-- Table rows loaded dynamically -->
                    </tbody>
                </table>
            </section>"""

    @staticmethod
    def _generate_form_component(component) -> str:
        """Generate form component HTML"""
        entity = component.entity_binding or "Item"
        fields = component.properties.get("fields", [])

        form_fields = []
        for field in fields:
            field_name = field.get("name", "field")
            field_type = field.get("type", "text")
            required = field.get("required", False)
            description = field.get("description", "")

            input_type = "text"
            if field_type == "integer":
                input_type = "number"
            elif field_type == "boolean":
                input_type = "checkbox"
            elif field_type == "timestamp":
                input_type = "datetime-local"
            elif field_type == "date":
                input_type = "date"

            required_attr = "required" if required else ""
            form_fields.append(
                f'                    <div class="form-group">\n'
                f'                        <label for="{field_name}">{field_name}</label>\n'
                f'                        <input type="{input_type}" id="{field_name}" name="{field_name}" {required_attr}>\n'
                f'                        <small>{description}</small>\n'
                f'                    </div>'
            )

        form_content = "\n".join(form_fields)

        return f"""            <section class="component component-form">
                <h2>{entity} Form</h2>
                <form id="{entity.lower()}-form" class="data-form">
{form_content}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="reset" class="btn btn-secondary">Clear</button>
                    </div>
                </form>
            </section>"""

    @staticmethod
    def _generate_button_component(component) -> str:
        """Generate button component HTML"""
        label = component.properties.get("label", "Button")
        return f'            <button class="btn btn-primary">{label}</button>'

    @staticmethod
    def _generate_stat_cards_component(component) -> str:
        """Generate statistics cards component"""
        return """            <section class="component component-stats">
                <div class="stats-grid">
                    <div class="stat-card">
                        <h3>Total Items</h3>
                        <p class="stat-value" id="stat-total">0</p>
                    </div>
                    <div class="stat-card">
                        <h3>This Month</h3>
                        <p class="stat-value" id="stat-month">0</p>
                    </div>
                    <div class="stat-card">
                        <h3>This Week</h3>
                        <p class="stat-value" id="stat-week">0</p>
                    </div>
                    <div class="stat-card">
                        <h3>Today</h3>
                        <p class="stat-value" id="stat-today">0</p>
                    </div>
                </div>
            </section>"""

    @staticmethod
    def _generate_chart_component(component) -> str:
        """Generate chart component"""
        return """            <section class="component component-chart">
                <div id="chart-container" style="height: 400px;">
                    <!-- Chart will be rendered here by chart library -->
                </div>
            </section>"""

    @staticmethod
    def _generate_header_component(component) -> str:
        """Generate header component"""
        title = component.properties.get("title", "Application")
        description = component.properties.get("description", "")

        return f"""            <header class="component component-header">
                <h1>{title}</h1>
                <p class="description">{description}</p>
            </header>"""

    @staticmethod
    def _generate_nav_component(component) -> str:
        """Generate navigation component"""
        return """            <nav class="component component-nav">
                <ul class="nav-menu">
                    <li><a href="/">Dashboard</a></li>
                    <li><a href="/entities">Entities</a></li>
                    <li><a href="/settings">Settings</a></li>
                </ul>
            </nav>"""
