class ReadmeGenerator:

    @staticmethod
    def generate(
        app_name: str
    ) -> str:

        return f"""
# {app_name}

Generated by AI App Compiler.

## Setup

Create a virtual environment:

python -m venv .venv

Activate:

source .venv/bin/activate

Install dependencies:

pip install -r requirements.txt

Run:

python app.py

Open:

http://127.0.0.1:5000
"""